name: dbt Slim CI pipeline

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'dbt/**'

jobs:
  dbt-slim-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install dbt-snowflake

      - name: Run dbt Slim CI
        run: |
          dbt deps --project-dir ./dbt
          dbt build --project-dir ./dbt --select state:modified+ --defer --state ./state
